# CI for Explorevent - yarn

name: Explorevent CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          CI: false
          REACT_APP_CLIENT_TINYAPI_KEY: ${{ secrets.REACT_APP_CLIENT_TINYAPI_KEY }}
          REACT_APP_CLIENT_DROPBOX_KEY: ${{ secrets.REACT_APP_CLIENT_DROPBOX_KEY }}
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          ATLAS_DBNAME: ${{ secrets.ATLAS_DBNAME }}
          DM_MODERATOR_API_URL: ${{ secrets.DM_MODERATOR_API_URL }}
          DM_MODERATOR_API_KEY: ${{ secrets.DM_MODERATOR_API_KEY }}
          DM_SPAM_API_URL: ${{ secrets.DM_SPAM_API_URL }}
          AKISMET_API_KEY: ${{ secrets.AKISMET_API_KEY }}
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          SECRET: ${{ secrets.SECRET }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
